version: '3.8'

services:
  app:
    build: .
    container_name: rag-app
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    networks:
      - ollama-docker

  ollama:
    hostname: ollama-container
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker


networks:
  ollama-docker:
    external: false

